-- Disable RLS on all tables during migration
-- Will re-enable with proper policies after migration is complete
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.leagues DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.players DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rosters DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.drafts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pick_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rookie_draft_picks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.draft_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.projected_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.previous_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.regular_season_rosters DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_fees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.keeper_fees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.wagers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.watchlists DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.prospects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolios DISABLE ROW LEVEL SECURITY;
